apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-purger
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: thumbor-deployment-7f4f4f9466-vr7zc
            command: ["/bin/sh", "-c"]
            args: ["find /data/thumbor/storage -type f -mtime +7 -atime +1 -exec rm -rf {} \\;"]
            volumeMounts:
            - name: storage
              mountPath: /data/thumbor/storage
          restartPolicy: OnFailure
          volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: thumbor-pvc
